	select CAST(ride_id as nvarchar) as ride_id,
	CAST(rideable_type as nvarchar) as rideable_type,
	CAST(started_at as datetime) as started_at,
	CAST(ended_at as nvarchar) as ended_at,
	CAST(start_station_name as nvarchar(max)) as start_station_name,
	CAST(start_station_id as nvarchar) as start_station_id,
	CAST(end_station_name as nvarchar(max)) as end_station_name,
	CAST(end_station_id as nvarchar) as end_station_id,
	CONCAT(CAST(start_station_name as nvarchar(max)), ' -- ', CAST(end_station_name as nvarchar(max))) as route,
	CAST(start_lat as float) as start_lat,
	CAST(start_lng as float) as start_lng,
	CAST(end_lat as float) as end_lat,
	CAST(end_lng as float) as end_lng,
	CAST(member_casual as nvarchar) as member_casual, 
	DATEDIFF(MINUTE,started_at, ended_at) as trip_len, 
	DATEPART(MONTH, started_at) as Month,
	datename(MM,started_at) as MonthName,
	DATEPART(QUARTER, started_at) as Quarter,
	datename(WEEKDAY, started_at) as WeekDay
	into bike_share.dbo.[alltrips] from bike_share.dbo.[202112-divvy-tripdata]
		union all
	select CAST(ride_id as nvarchar) as ride_id,
	CAST(rideable_type as nvarchar) as rideable_type,
	CAST(started_at as datetime) as started_at,
	CAST(ended_at as nvarchar) as ended_at,
	CAST(start_station_name as nvarchar(max)) as start_station_name,
	CAST(start_station_id as nvarchar) as start_station_id,
	CAST(end_station_name as nvarchar(max)) as end_station_name,
	CAST(end_station_id as nvarchar) as end_station_id,
	CONCAT(CAST(start_station_name as nvarchar(max)), ' -- ', CAST(end_station_name as nvarchar(max))) as route,
	CAST(start_lat as float) as start_lat,
	CAST(start_lng as float) as start_lng,
	CAST(end_lat as float) as end_lat,
	CAST(end_lng as float) as end_lng,
	CAST(member_casual as nvarchar) as member_casual, 
	DATEDIFF(MINUTE,started_at, ended_at) as trip_len, 
	DATEPART(MONTH, started_at) as Month,
	datename(MM,started_at) as MonthName,
	DATEPART(QUARTER, started_at) as Quarter,
	datename(WEEKDAY, started_at) as WeekDay
	from bike_share.dbo.[202201-divvy-tripdata]
		union all

	select CAST(ride_id as nvarchar) as ride_id,
	CAST(rideable_type as nvarchar) as rideable_type,
	CAST(started_at as datetime) as started_at,
	CAST(ended_at as nvarchar) as ended_at,
	CAST(start_station_name as nvarchar(max)) as start_station_name,
	CAST(start_station_id as nvarchar) as start_station_id,
	CAST(end_station_name as nvarchar(max)) as end_station_name,
	CAST(end_station_id as nvarchar) as end_station_id,
	CONCAT(CAST(start_station_name as nvarchar(max)), ' -- ', CAST(end_station_name as nvarchar(max))) as route,
	CAST(start_lat as float) as start_lat,
	CAST(start_lng as float) as start_lng,
	CAST(end_lat as float) as end_lat,
	CAST(end_lng as float) as end_lng,
	CAST(member_casual as nvarchar) as member_casual, 
	DATEDIFF(MINUTE,started_at, ended_at) as trip_len, 
	DATEPART(MONTH, started_at) as Month,
	datename(MM,started_at) as MonthName,
	DATEPART(QUARTER, started_at) as Quarter,
	datename(WEEKDAY, started_at) as WeekDay
	from bike_share.dbo.[202202-divvy-tripdata]
		union all

	select CAST(ride_id as nvarchar) as ride_id,
	CAST(rideable_type as nvarchar) as rideable_type,
	CAST(started_at as datetime) as started_at,
	CAST(ended_at as nvarchar) as ended_at,
	CAST(start_station_name as nvarchar(max)) as start_station_name,
	CAST(start_station_id as nvarchar) as start_station_id,
	CAST(end_station_name as nvarchar(max)) as end_station_name,
	CAST(end_station_id as nvarchar) as end_station_id,
	CONCAT(CAST(start_station_name as nvarchar(max)), ' -- ', CAST(end_station_name as nvarchar(max))) as route,
	CAST(start_lat as float) as start_lat,
	CAST(start_lng as float) as start_lng,
	CAST(end_lat as float) as end_lat,
	CAST(end_lng as float) as end_lng,
	CAST(member_casual as nvarchar) as member_casual, 
	DATEDIFF(MINUTE,started_at, ended_at) as trip_len, 
	DATEPART(MONTH, started_at) as Month,
	datename(MM,started_at) as MonthName,
	DATEPART(QUARTER, started_at) as Quarter,
	datename(WEEKDAY, started_at) as WeekDay
	from bike_share.dbo.[202203-divvy-tripdata]
		union all

	select CAST(ride_id as nvarchar) as ride_id,
	CAST(rideable_type as nvarchar) as rideable_type,
	CAST(started_at as datetime) as started_at,
	CAST(ended_at as nvarchar) as ended_at,
	CAST(start_station_name as nvarchar(max)) as start_station_name,
	CAST(start_station_id as nvarchar) as start_station_id,
	CAST(end_station_name as nvarchar(max)) as end_station_name,
	CAST(end_station_id as nvarchar) as end_station_id,
	CONCAT(CAST(start_station_name as nvarchar(max)), ' -- ', CAST(end_station_name as nvarchar(max))) as route,
	CAST(start_lat as float) as start_lat,
	CAST(start_lng as float) as start_lng,
	CAST(end_lat as float) as end_lat,
	CAST(end_lng as float) as end_lng,
	CAST(member_casual as nvarchar) as member_casual, 
	DATEDIFF(MINUTE,started_at, ended_at) as trip_len, 
	DATEPART(MONTH, started_at) as Month,
	datename(MM,started_at) as MonthName,
	DATEPART(QUARTER, started_at) as Quarter,
	datename(WEEKDAY, started_at) as WeekDay
	from bike_share.dbo.[202204-divvy-tripdata]
		union all

	select CAST(ride_id as nvarchar) as ride_id,
	CAST(rideable_type as nvarchar) as rideable_type,
	CAST(started_at as datetime) as started_at,
	CAST(ended_at as nvarchar) as ended_at,
	CAST(start_station_name as nvarchar(max)) as start_station_name,
	CAST(start_station_id as nvarchar) as start_station_id,
	CAST(end_station_name as nvarchar(max)) as end_station_name,
	CAST(end_station_id as nvarchar) as end_station_id,
	CONCAT(CAST(start_station_name as nvarchar(max)), ' -- ', CAST(end_station_name as nvarchar(max))) as route,
	CAST(start_lat as float) as start_lat,
	CAST(start_lng as float) as start_lng,
	CAST(end_lat as float) as end_lat,
	CAST(end_lng as float) as end_lng,
	CAST(member_casual as nvarchar) as member_casual, 
	DATEDIFF(MINUTE,started_at, ended_at) as trip_len, 
	DATEPART(MONTH, started_at) as Month,
	datename(MM,started_at) as MonthName,
	DATEPART(QUARTER, started_at) as Quarter,
	datename(WEEKDAY, started_at) as WeekDay
	from bike_share.dbo.[202205-divvy-tripdata]
		union all

	select CAST(ride_id as nvarchar) as ride_id,
	CAST(rideable_type as nvarchar) as rideable_type,
	CAST(started_at as datetime) as started_at,
	CAST(ended_at as nvarchar) as ended_at,
	CAST(start_station_name as nvarchar(max)) as start_station_name,
	CAST(start_station_id as nvarchar) as start_station_id,
	CAST(end_station_name as nvarchar(max)) as end_station_name,
	CAST(end_station_id as nvarchar) as end_station_id,
	CONCAT(CAST(start_station_name as nvarchar(max)), ' -- ', CAST(end_station_name as nvarchar(max))) as route,
	CAST(start_lat as float) as start_lat,
	CAST(start_lng as float) as start_lng,
	CAST(end_lat as float) as end_lat,
	CAST(end_lng as float) as end_lng,
	CAST(member_casual as nvarchar) as member_casual, 
	DATEDIFF(MINUTE,started_at, ended_at) as trip_len, 
	DATEPART(MONTH, started_at) as Month,
	datename(MM,started_at) as MonthName,
	DATEPART(QUARTER, started_at) as Quarter,
	datename(WEEKDAY, started_at) as WeekDay
	from bike_share.dbo.[202206-divvy-tripdata]
		union all

	select CAST(ride_id as nvarchar) as ride_id,
	CAST(rideable_type as nvarchar) as rideable_type,
	CAST(started_at as datetime) as started_at,
	CAST(ended_at as nvarchar) as ended_at,
	CAST(start_station_name as nvarchar(max)) as start_station_name,
	CAST(start_station_id as nvarchar) as start_station_id,
	CAST(end_station_name as nvarchar(max)) as end_station_name,
	CAST(end_station_id as nvarchar) as end_station_id,
	CONCAT(CAST(start_station_name as nvarchar(max)), ' -- ', CAST(end_station_name as nvarchar(max))) as route,
	CAST(start_lat as float) as start_lat,
	CAST(start_lng as float) as start_lng,
	CAST(end_lat as float) as end_lat,
	CAST(end_lng as float) as end_lng,
	CAST(member_casual as nvarchar) as member_casual, 
	DATEDIFF(MINUTE,started_at, ended_at) as trip_len, 
	DATEPART(MONTH, started_at) as Month,
	datename(MM,started_at) as MonthName,
	DATEPART(QUARTER, started_at) as Quarter,
	datename(WEEKDAY, started_at) as WeekDay
	from bike_share.dbo.[202207-divvy-tripdata]
		union all

	select CAST(ride_id as nvarchar) as ride_id,
	CAST(rideable_type as nvarchar) as rideable_type,
	CAST(started_at as datetime) as started_at,
	CAST(ended_at as nvarchar) as ended_at,
	CAST(start_station_name as nvarchar(max)) as start_station_name,
	CAST(start_station_id as nvarchar) as start_station_id,
	CAST(end_station_name as nvarchar(max)) as end_station_name,
	CAST(end_station_id as nvarchar) as end_station_id,
	CONCAT(CAST(start_station_name as nvarchar(max)), ' -- ', CAST(end_station_name as nvarchar(max))) as route,
	CAST(start_lat as float) as start_lat,
	CAST(start_lng as float) as start_lng,
	CAST(end_lat as float) as end_lat,
	CAST(end_lng as float) as end_lng,
	CAST(member_casual as nvarchar) as member_casual, 
	DATEDIFF(MINUTE,started_at, ended_at) as trip_len, 
	DATEPART(MONTH, started_at) as Month,
	datename(MM,started_at) as MonthName,
	DATEPART(QUARTER, started_at) as Quarter,
	datename(WEEKDAY, started_at) as WeekDay
	from bike_share.dbo.[202208-divvy-tripdata]
		union all

	select CAST(ride_id as nvarchar) as ride_id,
	CAST(rideable_type as nvarchar) as rideable_type,
	CAST(started_at as datetime) as started_at,
	CAST(ended_at as nvarchar) as ended_at,
	CAST(start_station_name as nvarchar(max)) as start_station_name,
	CAST(start_station_id as nvarchar) as start_station_id,
	CAST(end_station_name as nvarchar(max)) as end_station_name,
	CAST(end_station_id as nvarchar) as end_station_id,
	CONCAT(CAST(start_station_name as nvarchar(max)), ' -- ', CAST(end_station_name as nvarchar(max))) as route,
	CAST(start_lat as float) as start_lat,
	CAST(start_lng as float) as start_lng,
	CAST(end_lat as float) as end_lat,
	CAST(end_lng as float) as end_lng,
	CAST(member_casual as nvarchar) as member_casual, 
	DATEDIFF(MINUTE,started_at, ended_at) as trip_len, 
	DATEPART(MONTH, started_at) as Month, 
	datename(MM,started_at) as MonthName,
	DATEPART(QUARTER, started_at) as Quarter,
	datename(WEEKDAY, started_at) as WeekDay 
	from bike_share.dbo.[202209-divvy-publictripdata]
	where start_station_name is not null or end_station_name is not null or start_station_name = end_station_name
		union all

	select CAST(ride_id as nvarchar) as ride_id,
	CAST(rideable_type as nvarchar) as rideable_type,
	CAST(started_at as datetime) as started_at,
	CAST(ended_at as nvarchar) as ended_at,
	CAST(start_station_name as nvarchar(max)) as start_station_name,
	CAST(start_station_id as nvarchar) as start_station_id,
	CAST(end_station_name as nvarchar(max)) as end_station_name,
	CAST(end_station_id as nvarchar) as end_station_id,
	CONCAT(CAST(start_station_name as nvarchar(max)), ' -- ', CAST(end_station_name as nvarchar(max))) as route,
	CAST(start_lat as float) as start_lat,
	CAST(start_lng as float) as start_lng,
	CAST(end_lat as float) as end_lat,
	CAST(end_lng as float) as end_lng,
	CAST(member_casual as nvarchar) as member_casual, 
	DATEDIFF(MINUTE,started_at, ended_at) as trip_len, 
	DATEPART(MONTH, started_at) as Month,
	datename(MM,started_at) as MonthName,
	DATEPART(QUARTER, started_at) as Quarter,
	datename(WEEKDAY, started_at) as WeekDay 
	from bike_share.dbo.[202210-divvy-tripdata]
	

